name: ashe actions

on:
  push:
  branches: [ master ]

jobs:

  runAshe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test

    - name: Run
      run: |
        make